return {
  require('plugins.colorizer'),
  require('plugins.themes'),
  require('plugins.nvim-tree'),
  require('plugins.laravel-nvim'),
  require('plugins.lualine'),
  require('plugins.no-setup-plugins'),
  require('plugins.lspconfig'),
  require('plugins.nvim-cmp'),
  require('plugins.nvim-telescope'),
  require('plugins.indent-blankline'),
  require('plugins.gitsigns'),
  require('plugins.nvim-treesitter'),
  require('keybindings'),
}
